FROM node:18-bullseye
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --silent

# Copy source files
COPY . .

EXPOSE 5173

# Start development server
CMD ["npm", "run", "dev"]
